### ISSUE TITLE
how to ask as question to this service from different service..

### ISSUE THREAD

**Issue by snatuva** [BoChengHuang/Bluemix_RR_Nodejs#1]

**Comment by BoChengHuang** [comment]
Hello! Can you provide an example?
If you mean that you develop other application with wants to use R&R without Node.js,
you can use HTTP POST/GET.
FYI, [API reference](https://www.ibm.com/watson/developercloud/retrieve-and-rank/api/v1/)

**Comment by snatuva** [comment]
For  example the chat bot.. if a user asks questions, and that question is out of my limit.. i want to use this service for a related answer atleast.. Totally i am using this with Node.

**Comment by BoChengHuang** [comment]
If you already have a chat bot, I recommend you that you just use Watson API on Bluemix in you app by HTTP POST/GET, that will be simple.
But you should training Watson first on Bluemix.

FYI, Use [this](https://github.com/request/request) in your node.js code to request API.
Good luck.
